# first stage: build
FROM golang:1.21-alpine AS builder

# set work directory
WORKDIR /app

# install necessary dependencies
RUN apk add --no-cache gcc musl-dev git

# copy project source code
COPY . .

# Download all dependencies and tidy up
RUN go mod download && \
    go get -t ./... && \
    go mod tidy && \
    go mod verify

# build binary
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api

# final stage
FROM golang:1.21-alpine

WORKDIR /app

# install necessary dependencies
RUN apk add --no-cache gcc musl-dev git

# copy project source code and binary
COPY . .
COPY --from=builder /app/main .
COPY --from=builder /go/pkg/mod /go/pkg/mod

# expose port
EXPOSE 8080

# run binary
CMD ["./main"]